# Generated by Django 4.2.30 on 2026-04-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandhistory',
            name='ai_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='commandhistory',
            name='ai_raw_output',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='commandhistory',
            name='ai_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commandhistory',
            name='parsed_action',
            field=models.CharField(blank=True, default='draft', max_length=40),
        ),
        migrations.AddField(
            model_name='commandhistory',
            name='parsed_occasion',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='commandhistory',
            name='parsed_schedule_time',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
