# Generated by Django 4.2.30 on 2026-04-11 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0002_contact_anniversary_date_contact_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True, default='')),
                ('reminder_type', models.CharField(choices=[('custom', 'Custom'), ('birthday', 'Birthday'), ('anniversary', 'Anniversary')], default='custom', max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('auto_send_email', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=100)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='contacts.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['user', 'scheduled_for'], name='reminders_r_user_id_2973c3_idx'), models.Index(fields=['status', 'scheduled_for'], name='reminders_r_status_42a620_idx'), models.Index(fields=['idempotency_key'], name='reminders_r_idempot_7625be_idx')],
            },
        ),
    ]
